### ISSUE TITLE
Karon has last name in csv

### ISSUE THREAD

**Issue by thehesiod** [carltonnorthern/nicknames#13]
`karonhappuck`

see: https://github.com/carltonnorthern/nickname-and-diminutive-names-lookup/blob/master/names.csv#L573

**Comment by thehesiod** [comment]
based on that unique name, looks like your DB may be used here: http://www.caagri.org/nicknames.html

**Comment by thehesiod** [comment]
sorry, another we have concern with, Ben in: `jamie,james,ben`.  I would imagine Ben is short for Benjamin. And Jamie -> James.  But don't see the connection to Ben.

**Comment by carltonnorthern** [comment]
I think "happy" must be a nickname for the "happuck" part of "karonhappuck".  I got the initial list of names for this lookup from a Genealogy website credited in the README.  It looks like that list is no longer on their website but potentially at the link you provided?  So its probably that I used their DB?

**Comment by carltonnorthern** [comment]
I've removed the "ben" in question.  Thank you.

**Comment by thehesiod** [comment]
fascinating, thanks!
