### ISSUE TITLE
Consider renaming repo to `us-nicknames`

### ISSUE THREAD

**Issue by NickCrews** [carltonnorthern/nicknames#39]
existing name is quite verbose. Then it would match the python package name. I think all existing links should be redirected.

**Comment by carltonnorthern** [comment]
I think this sounds like a reasonable idea.  Can anyone think of a reason not to rename it?

**Comment by NickCrews** [comment]
Tagging everyone who's contributed in the last 2 years, in case anyone wants to weigh in. Feel free to ignore, and sorry for the spam!

@KenLewis @f0rk @c0bra @gpilgrim2670 @cwag03 @CalvinWu4 @louking @danielleevandenbosch @ITernovtsiy @lockster99

**Comment by f0rk** [comment]
👍🏻 from me

**Comment by KenLewis** [comment]
I think "nicknames" would be better as it's not just US names. They are English country names. 

My only concern about changing the name would be the Google search results for years of it being the current name. That's how I found this great repo. If you rename it, I suggest creating a new repo with the old name that just has a readme that points to the new one. 

Just my two cents.

**Comment by mdahlman** [comment]
I'm with @KenLewis: be bold and go for "nicknames" with the idea that this covers all English language nicknames.

Conceivably at the data level one could add files like `names-uk.csv` someday if they ever wanted to differentiate nicknames that were only in common use somewhere else. But I speculate this would be more trouble than it's worth for most folks.

Likewise, keeping or re-creating "nickname-and-diminutive-names-lookup" just for search purposes is a great idea.

**Comment by louking** [comment]
Not a contributor, but here's a user's perspective. My use case is to find nicknames in a pool of people whose nationality isn't known. I think the database could potentially support non-English names/nicknames. So why limit it via the repo name? 

I.e., I support use of 'nicknames' if that's not already used.

Uh, oops -- looks like 'us-nicknames' has already been published: https://pypi.org/project/us-nicknames/

**Comment by NickCrews** [comment]
OK, removing the `us-` prefix sounds fine to me. I was hesitant to claim the name of just `nicknames` on PyPI, that seemed like such a desirable and general name that I wanted to leave it available. Think I'm being silly there, should we just claim it?

Or should we be more precise, and mention that this is a hand-curated list? I think this might differentiate us from other projects. Could do
- nickname-list
- nickname-roundup
- nickname-compendium
- nickname-anthology

I think `nicknames` or `nickname-roundup` (🤠 lol) are my top choices. 

> Uh, oops -- looks like 'us-nicknames' has already been published: https://pypi.org/project/us-nicknames/

Not a big deal the PyPI package is published already, it's version 0.1.0 so we can remove it. Probably should do it pretty soon though.

**Comment by louking** [comment]
If I had a vote (I don't think I do), I would name it simply "nicknames" or "nickname-lookup". Sorry I don't like "-roundup" as I guess I don't know what it means in this context.

**Comment by carltonnorthern** [comment]
Sounds like everyone is good with `nicknames`.  Sounds good to me.  Should we go ahead and make the name change before we update the pipeline with Pypi API token @NickCrews ?

**Comment by carltonnorthern** [comment]
Ok, I made the change and it looks like the links automatically forward from the old repo to the new repo.  Doing a search on Google for `nicknames github` and clicking on the old repo result automatically forwards to the new repo.  If that's the case, I think creating a repo with the old name that points to the new repo may actually hurt us more than help us.  Thoughts?

**Comment by NickCrews** [comment]
Sweet thanks! I vote no on creating a new repo, Google is smart and they'll figure it out that they are the same.
