### ISSUE TITLE
Get PyPI tokens set up

### ISSUE THREAD

**Issue by NickCrews** [carltonnorthern/nicknames#41]
- [x] @carltonnorthern verify your email on test pypi, I tried adding you and got "User 'carlton.northern' does not have a verified primary email address and cannot be added as a Owner for project"
- [x] @NickCrews add carlton as a co-owner
- [ ] @carltonnorthern set up API tokens for test and prod pypi. This is quite easy, should only take 5 minutes for each
    - [x] Read https://pypi.org/help/#apitoken
    - [x] Make a token
    - [x] on this github repo, go to its Settings, then on the sidebar "Secrets" > "repository". On the new page click "New repository secret" and then you have to name them PYPI_API_TOKEN and TEST_PYPI_API_TOKEN so they match https://github.com/carltonnorthern/nickname-and-diminutive-names-lookup/blob/d2c7c72fa1324db0a339bf5daf04e518034a3574/.github/workflows/ci.yml#L90-L98

**Comment by NickCrews** [comment]
@carltonnorthern back to you :)

**Comment by NickCrews** [comment]
@carltonnorthern Just deleted the us-nicknames packages and re-invited you to the `nicknames` packages. Sorry for the churn!

**Comment by carltonnorthern** [comment]
Completed.  Looks like pipelines are operational now!
