### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by fersarr** [carltonnorthern/nicknames#44]
Hi,

Thanks for creating this useful package. It seems the documentation is out of date or out of sync with the package in pypi:

```
Python 3.9.12 (main, Apr  5 2022, 01:53:17)
>>> from us_nicknames import NickNamer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'NickNamer' from 'us_nicknames' 
```

I do have the latest one (pip installed today)
```
>>> import us_nicknames
>>> us_nicknames.__version__
'0.1.2'
```

**Comment by carltonnorthern** [comment]
Hi @fersarr, we're in the process of renaming.  Pardon our dust for the next day or two while we change the name to `nicknames`.

**Comment by NickCrews** [comment]
@fersarr it should work now with `nicknames==0.1.1`. Please re-open if it doesn't!

**Comment by fersarr** [comment]
Thank you!
