### ISSUE TITLE
Browse through some of the forked repos and bring improvements back into this repo

### ISSUE THREAD

**Issue by carltonnorthern** [carltonnorthern/nicknames#7]

**Comment by djlambert** [comment]
Just did this, the only forks with any changes are:

mdahlman/nickname-and-diminutive-names-lookup
yooper/nicknames

**Comment by carltonnorthern** [comment]
Thanks!  I'll take a look.

**Comment by NickCrews** [comment]
Closing as not actionable/time-bounded.
